### ISSUE TITLE
Security Problem.

### ISSUE THREAD

**Issue by ghost** [AshstarTempest/SQL-Simplified-Python-Edition#2]
Hello! I checked your code on Github Global Campus and these are some issues i saw:

In the "main.py" create_table function, there's a missing closing parenthesis in the "subject_name VARCHAR(255".

Your code constructs SQL queries by directly injecting user input, which can make your code vulnerable to SQL injection attacks.
You must use parameterized queries or prepared statements to safely handle user input.

Other than these issues, your code looks nice. Good work with the project!

**Comment by RemasteredGod** [comment]
Currently I have broken this project into subparts and will later combine them to main.py as this is a big project but your issue is really important so for that I have thought of validating the imports and then set a time limit
